language: android
os:
  - linux
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
android:
  components:
    - build-tools-23.0.1
    - platform-tools
    - tools
    - extra
script:
  - curl -o sbt-launcher.sh https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt
  - chmod a+x ./sbt-launcher.sh
  - ./sbt-launcher.sh compile scripted
